include 'Skills/Skill'
include 'Skills/SkillSet'

include 'Skills/DefaultSkill'
include 'Skills/DanceSkill'
include 'Skills/TreeFarmSkill'
include 'Skills/ChopTreeSkill'
include 'Skills/GatherSandSkill'
include 'Skills/NeedleMineSkill'
include 'Skills/CraftItemSkill'
